name: Update Gallery

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # every 6 hours

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Chrome, ChromeDriver, and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip xvfb google-chrome-stable chromium-chromedriver
          # Link chromedriver for compatibility with selenium default path
          sudo ln -sf /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver || true


      - name: Install Python dependencies
        run: pip install selenium requests beautifulsoup4

      - name: Scrape images with Selenium
        run: xvfb-run python scripts/scrape_figment2.py

      - name: Update gallery HTML
        run: python scripts/update_gallery.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add images/*.jpg images/*.png gallery.html || true
          git commit -m "Update gallery images and HTML" || echo "No changes to commit"
          git push